### PR TITLE
Add support to more methods

### PR DESCRIPTION
**Pull request by duduribeiro**
This PR will allow libphonenumber to wrap more methods from the original lib. I wrap these to list the supported regions from libphonenumber.

Thanks

:beers:

### CODE REVIEW

**Comment by marco-faustinelli** [comment]
It seems interesting. The file size increase seems reasonable. Why are there only the files up to BL, and not those for all countries?

... but I can't see the `build.sh` and `build.xml` that you used to compile your files.

**Comment by duduribeiro** [comment]
There are files for all countries in the change.. no?

I used the same `build.sh` and `build.xml`

**Comment by nathanhammond** [comment]
Looks good to me. Can you modify this to be two commits? One for the underlying change, one for the `dist` changes? Will merge at that point. :)

**Comment by duduribeiro** [comment]
@nathanhammond changed, can u check if it is ok?

Thanks :beers: 
=D

**Comment by nathanhammond** [comment]
Excellent. Thanks!

**Comment by marco-faustinelli** [comment]
I was wrong. I only counted the modified files and not the new ones.

If all this can be done using the same build files, then I am still missing something about this library. My view was that one has to tailor the compilation to suit his/her own needs. I'll study more :-)

**Pull request merged**
